### ISSUE TITLE
Error: Error: EACCES: permission denied, mkdir 

### ISSUE THREAD

**Issue by mafreud** [open-ci-io/openci#17]
```yaml
- name: setup ruby
  uses: ruby/setup-ruby@v1
    with:
    ruby-version: .ruby-version
```

Using 3.1.2 as input from file .ruby-version
Modifying PATH
Error: Error: EACCES: permission denied, mkdir '/Users/runner'
at async Object.mkdir (node:internal/fs/promises:855:10)
