### ISSUE TITLE
ERROR: While executing gem ... 

### ISSUE THREAD

**Issue by mafreud** [open-ci-io/openci#18]
```yaml
- name: install danger
   run: |
     gem install bundler
     bundle install
```

Run gem install bundler
ERROR: While executing gem ... (Gem::FilePermissionError)
You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory.
Error: Process completed with exit code 1.
